### ISSUE TITLE
Icons 

### ISSUE THREAD

**Issue by sembrestels** [1Hive/apiary#126]
**Is your feature request related to a problem? Please describe.**
Some icons does not show in the apps tab: https://apiary.1hive.org/apps

**Describe the solution you'd like**
I would get the icon from the app itself (looking it in the app's manifest.json)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by onbjerg** [comment]
The reason this is happening is because we're syncing from the genesis DAO block up to the latest block right now, and the icons are derived from the manifest at the last version indexed. The worker indexes old versions right now (even though they already exist) and this overrides the icon.

I'm going to keep this issue though, since it would be nice to just compare if the version the worker is looking at is an older one (or an indexed one) and skipping the manifest entirely in that case.

**Comment by onbjerg** [comment]
Should be fixed after #200 since the icons are available in the subgraph
