### ISSUE TITLE
Discuss the pros/cons of using the The Graph

### ISSUE THREAD

**Issue by lkngtn** [1Hive/apiary#78]
Currently Apiary is a centralized application, like a block explorer. We could potentially decentralize part of the backend by leveraging The Graph. Or we could stick with a centralized backend for simplicity and flexibility. 

I lean towards the later, but wanted to make sure there was an issue to discuss this topic.

**Comment by onbjerg** [comment]
There are some things that we simply cannot do with The Graph at the moment, such as traces for activity tracking. Custom user data (such as tagging organisations etc.) also wouldn't really work. We could theoretically do these things on the side, but it would mean that we would have to adhere to their GraphQL schema for everything we do on top.

Furthermore, we lose control of the schema, which might seem small but does mean that we probably can't iterate as fast.

Lastly, there would be some added overhead for people contributing, since they would have to have knowledge of The Graph, and they would also have to run The Graph locally for local development on top of what we already have.

I lean strongly towards just rolling our own, although I do admit The Graph looks cool.

**Comment by lkngtn** [comment]
That rationale makes sense to me.

**Comment by onbjerg** [comment]
We're moving (#200)
